# Generated by Django 2.1 on 2018-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedio', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('disid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presc',
                'managed': False,
            },
        ),
    ]
